/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectwithswing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon; 
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author User
 */
public class pages extends javax.swing.JFrame {
    public DefaultTableModel model,modelforBazar;
    public String[] com = {"Name","Break Fast","Lunch","Diner","Total Meal","Date"};
    public String[] comForBazar = {"                Name","                Item","              Amount","                Date"};
    public String[] row = new String[6]; 
    public String[] rowForBazar = new String[4]; 
    public String[] name = {"Md Tasluf Morsehed","Assadijjaman Tilok","Sayed Mohammed Ishtiaq","Md. Mosarof Korim","Relatives"};
    public pages() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(com);
        
        modelforBazar = new DefaultTableModel();
        modelforBazar.setColumnIdentifiers(comForBazar);
        
        initComponents();
        this.setSize(800,500);
        this.setLocationRelativeTo(null);
        
        this.UserPage.setVisible(true);
        this.MealPage.setVisible(false);
        this.BazarPage.setVisible(false);
        this.BillPage.setVisible(false);
        this.AmountPage.setVisible(false);
        
       
        
    }
    public ImageIcon IconScale(String s)
    {
        ImageIcon icon = new ImageIcon("src/img/"+s);
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(27,27, Image.SCALE_SMOOTH);
        icon = new ImageIcon(newImage);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLeftPanel = new javax.swing.JPanel();
        MainLeftPanelUserIcon = new javax.swing.JLabel();
        MainLeftPanelMealIcon = new javax.swing.JLabel();
        MainLeftPanelBazarIcon = new javax.swing.JLabel();
        MainLeftPanelBillIcon = new javax.swing.JLabel();
        MainLeftPanelAmountIcon = new javax.swing.JLabel();
        MainLeftPanelOptionIcon = new javax.swing.JLabel();
        MainLeftPanelUserButton = new javax.swing.JButton();
        MainLeftPanelMealButton = new javax.swing.JButton();
        MainLeftPanelBazarButton = new javax.swing.JButton();
        MainLeftPanelBillButton = new javax.swing.JButton();
        MainLeftPanelAmountButton = new javax.swing.JButton();
        MainLeftPanelOptionButton = new javax.swing.JButton();
        UserPage = new javax.swing.JPanel();
        UserPageUpPanel = new javax.swing.JPanel();
        User = new javax.swing.JLabel();
        User2 = new javax.swing.JLabel();
        User3 = new javax.swing.JLabel();
        User4 = new javax.swing.JLabel();
        Ishtiaq = new javax.swing.JButton();
        Tasluf = new javax.swing.JButton();
        Tilok = new javax.swing.JButton();
        Mosarof = new javax.swing.JButton();
        UserPageIshtiaqPanel = new javax.swing.JPanel();
        Address2 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Mobile2 = new javax.swing.JLabel();
        Blood2 = new javax.swing.JLabel();
        UserPageRhymePanel = new javax.swing.JPanel();
        Address = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Mobile = new javax.swing.JLabel();
        Blood = new javax.swing.JLabel();
        UserPageTilokPanel = new javax.swing.JPanel();
        Address1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Mobile1 = new javax.swing.JLabel();
        Blood1 = new javax.swing.JLabel();
        UserPageMosarofPanel = new javax.swing.JPanel();
        Address3 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Mobile3 = new javax.swing.JLabel();
        Blood3 = new javax.swing.JLabel();
        MealPage = new javax.swing.JPanel();
        MealPanelUpPanel = new javax.swing.JPanel();
        MealPageName = new javax.swing.JLabel();
        MealPageDate = new javax.swing.JLabel();
        MealPageDateField = new javax.swing.JTextField();
        MealPageNameComboBox = new javax.swing.JComboBox<>();
        MealPageDinner = new javax.swing.JCheckBox();
        MealPageBreakFast = new javax.swing.JCheckBox();
        MealPageLunch = new javax.swing.JCheckBox();
        MealPageEditButton = new javax.swing.JButton();
        MealPageSubmitButton = new javax.swing.JButton();
        MealPanelDownPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BazarPage = new javax.swing.JPanel();
        MealPanelUpPanel1 = new javax.swing.JPanel();
        MealPageName1 = new javax.swing.JLabel();
        MealPageDate1 = new javax.swing.JLabel();
        MealPageDateField1 = new javax.swing.JTextField();
        MealPageNameComboBox1 = new javax.swing.JComboBox<>();
        MealPageEditButton1 = new javax.swing.JButton();
        MealPageSubmitButton1 = new javax.swing.JButton();
        MealPageDate2 = new javax.swing.JLabel();
        MealPageDateField2 = new javax.swing.JTextField();
        MealPageDate3 = new javax.swing.JLabel();
        MealPageDateField3 = new javax.swing.JTextField();
        MealPanelDownPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BillPage = new javax.swing.JPanel();
        AmountPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MainLeftPanel.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanel.setLayout(null);

        MainLeftPanelUserIcon.setBackground(new java.awt.Color(255, 255, 255));
        MainLeftPanelUserIcon.setIcon(IconScale("2703063-512.png"));
        MainLeftPanel.add(MainLeftPanelUserIcon);
        MainLeftPanelUserIcon.setBounds(40, 60, 27, 27);

        MainLeftPanelMealIcon.setIcon(IconScale("meal.png"));
        MainLeftPanel.add(MainLeftPanelMealIcon);
        MainLeftPanelMealIcon.setBounds(40, 120, 27, 27);

        MainLeftPanelBazarIcon.setIcon(IconScale("bazar.png"));
        MainLeftPanel.add(MainLeftPanelBazarIcon);
        MainLeftPanelBazarIcon.setBounds(40, 180, 27, 27);

        MainLeftPanelBillIcon.setIcon(IconScale("bill.png"));
        MainLeftPanel.add(MainLeftPanelBillIcon);
        MainLeftPanelBillIcon.setBounds(40, 240, 27, 27);

        MainLeftPanelAmountIcon.setIcon(IconScale("amount.png"));
        MainLeftPanel.add(MainLeftPanelAmountIcon);
        MainLeftPanelAmountIcon.setBounds(40, 300, 27, 27);

        MainLeftPanelOptionIcon.setIcon(IconScale("option.png"));
        MainLeftPanel.add(MainLeftPanelOptionIcon);
        MainLeftPanelOptionIcon.setBounds(40, 360, 27, 27);

        MainLeftPanelUserButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelUserButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelUserButton.setText("User");
        MainLeftPanelUserButton.setAlignmentY(1.0F);
        MainLeftPanelUserButton.setBorder(null);
        MainLeftPanelUserButton.setBorderPainted(false);
        MainLeftPanelUserButton.setContentAreaFilled(false);
        MainLeftPanelUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelUserButton.setFocusable(false);
        MainLeftPanelUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelUserButton.setIconTextGap(0);
        MainLeftPanelUserButton.setRequestFocusEnabled(false);
        MainLeftPanelUserButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelUserButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelUserButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelUserButton);
        MainLeftPanelUserButton.setBounds(80, 60, 80, 30);

        MainLeftPanelMealButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelMealButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelMealButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelMealButton.setText("Meal");
        MainLeftPanelMealButton.setAlignmentY(1.0F);
        MainLeftPanelMealButton.setBorder(null);
        MainLeftPanelMealButton.setBorderPainted(false);
        MainLeftPanelMealButton.setContentAreaFilled(false);
        MainLeftPanelMealButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelMealButton.setFocusable(false);
        MainLeftPanelMealButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelMealButton.setIconTextGap(0);
        MainLeftPanelMealButton.setRequestFocusEnabled(false);
        MainLeftPanelMealButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelMealButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelMealButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelMealButton);
        MainLeftPanelMealButton.setBounds(80, 120, 80, 30);

        MainLeftPanelBazarButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelBazarButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelBazarButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelBazarButton.setText("Bazar");
        MainLeftPanelBazarButton.setAlignmentY(1.0F);
        MainLeftPanelBazarButton.setBorder(null);
        MainLeftPanelBazarButton.setBorderPainted(false);
        MainLeftPanelBazarButton.setContentAreaFilled(false);
        MainLeftPanelBazarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelBazarButton.setFocusable(false);
        MainLeftPanelBazarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelBazarButton.setIconTextGap(0);
        MainLeftPanelBazarButton.setRequestFocusEnabled(false);
        MainLeftPanelBazarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelBazarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelBazarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelBazarButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelBazarButton);
        MainLeftPanelBazarButton.setBounds(80, 180, 80, 30);

        MainLeftPanelBillButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelBillButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelBillButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelBillButton.setText("Bill");
        MainLeftPanelBillButton.setAlignmentY(1.0F);
        MainLeftPanelBillButton.setBorder(null);
        MainLeftPanelBillButton.setBorderPainted(false);
        MainLeftPanelBillButton.setContentAreaFilled(false);
        MainLeftPanelBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelBillButton.setFocusable(false);
        MainLeftPanelBillButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelBillButton.setIconTextGap(0);
        MainLeftPanelBillButton.setRequestFocusEnabled(false);
        MainLeftPanelBillButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelBillButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelBillButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelBillButton);
        MainLeftPanelBillButton.setBounds(80, 240, 80, 30);

        MainLeftPanelAmountButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelAmountButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelAmountButton.setText("Amount");
        MainLeftPanelAmountButton.setAlignmentY(1.0F);
        MainLeftPanelAmountButton.setBorder(null);
        MainLeftPanelAmountButton.setBorderPainted(false);
        MainLeftPanelAmountButton.setContentAreaFilled(false);
        MainLeftPanelAmountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelAmountButton.setFocusable(false);
        MainLeftPanelAmountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelAmountButton.setIconTextGap(0);
        MainLeftPanelAmountButton.setRequestFocusEnabled(false);
        MainLeftPanelAmountButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelAmountButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelAmountButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelAmountButton);
        MainLeftPanelAmountButton.setBounds(80, 300, 80, 30);

        MainLeftPanelOptionButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelOptionButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelOptionButton.setText("Option");
        MainLeftPanelOptionButton.setAlignmentY(1.0F);
        MainLeftPanelOptionButton.setBorder(null);
        MainLeftPanelOptionButton.setBorderPainted(false);
        MainLeftPanelOptionButton.setContentAreaFilled(false);
        MainLeftPanelOptionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelOptionButton.setFocusable(false);
        MainLeftPanelOptionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelOptionButton.setIconTextGap(0);
        MainLeftPanelOptionButton.setRequestFocusEnabled(false);
        MainLeftPanelOptionButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelOptionButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelOptionButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelOptionButton);
        MainLeftPanelOptionButton.setBounds(80, 360, 80, 30);

        getContentPane().add(MainLeftPanel);
        MainLeftPanel.setBounds(0, 0, 200, 500);

        UserPage.setBackground(new java.awt.Color(204, 204, 204));
        UserPage.setAlignmentX(0.0F);
        UserPage.setFocusable(false);
        UserPage.setLayout(null);

        UserPageUpPanel.setBackground(new java.awt.Color(67, 47, 125));
        UserPageUpPanel.setLayout(null);

        User.setBackground(new java.awt.Color(255, 255, 255));
        User.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User);
        User.setBounds(80, 20, 27, 27);

        User2.setBackground(new java.awt.Color(255, 255, 255));
        User2.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User2);
        User2.setBounds(80, 70, 27, 27);

        User3.setBackground(new java.awt.Color(255, 255, 255));
        User3.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User3);
        User3.setBounds(350, 20, 27, 27);

        User4.setBackground(new java.awt.Color(255, 255, 255));
        User4.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User4);
        User4.setBounds(350, 70, 27, 27);

        Ishtiaq.setBackground(new java.awt.Color(43, 30, 72));
        Ishtiaq.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Ishtiaq.setForeground(new java.awt.Color(255, 255, 255));
        Ishtiaq.setText("Sayed Mohammed Ishtiaq");
        Ishtiaq.setAlignmentY(1.0F);
        Ishtiaq.setBorder(null);
        Ishtiaq.setBorderPainted(false);
        Ishtiaq.setContentAreaFilled(false);
        Ishtiaq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ishtiaq.setFocusable(false);
        Ishtiaq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ishtiaq.setIconTextGap(0);
        Ishtiaq.setRequestFocusEnabled(false);
        Ishtiaq.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Ishtiaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IshtiaqActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Ishtiaq);
        Ishtiaq.setBounds(120, 70, 200, 30);

        Tasluf.setBackground(new java.awt.Color(43, 30, 72));
        Tasluf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tasluf.setForeground(new java.awt.Color(255, 255, 255));
        Tasluf.setText("Md. Tasluf Morshed");
        Tasluf.setAlignmentY(1.0F);
        Tasluf.setBorder(null);
        Tasluf.setBorderPainted(false);
        Tasluf.setContentAreaFilled(false);
        Tasluf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tasluf.setFocusable(false);
        Tasluf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tasluf.setIconTextGap(0);
        Tasluf.setRequestFocusEnabled(false);
        Tasluf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tasluf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaslufActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Tasluf);
        Tasluf.setBounds(120, 20, 160, 30);

        Tilok.setBackground(new java.awt.Color(43, 30, 72));
        Tilok.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tilok.setForeground(new java.awt.Color(255, 255, 255));
        Tilok.setAlignmentY(1.0F);
        Tilok.setBorder(null);
        Tilok.setBorderPainted(false);
        Tilok.setContentAreaFilled(false);
        Tilok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tilok.setFocusable(false);
        Tilok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tilok.setIconTextGap(0);
        Tilok.setLabel("Assadujjman Tilok");
        Tilok.setRequestFocusEnabled(false);
        Tilok.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tilok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TilokActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Tilok);
        Tilok.setBounds(390, 20, 160, 30);

        Mosarof.setBackground(new java.awt.Color(43, 30, 72));
        Mosarof.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mosarof.setForeground(new java.awt.Color(255, 255, 255));
        Mosarof.setText("Md. Mosarof Korim");
        Mosarof.setAlignmentY(1.0F);
        Mosarof.setBorder(null);
        Mosarof.setBorderPainted(false);
        Mosarof.setContentAreaFilled(false);
        Mosarof.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mosarof.setFocusable(false);
        Mosarof.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mosarof.setIconTextGap(0);
        Mosarof.setRequestFocusEnabled(false);
        Mosarof.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Mosarof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosarofActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Mosarof);
        Mosarof.setBounds(390, 70, 160, 30);

        UserPage.add(UserPageUpPanel);
        UserPageUpPanel.setBounds(0, 60, 600, 120);

        UserPageIshtiaqPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageIshtiaqPanel.setLayout(null);

        Address2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address2.setText("Address: Sankor, Dhaka ");
        UserPageIshtiaqPanel.add(Address2);
        Address2.setBounds(280, 170, 210, 20);

        Name2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name2.setText("Name: Sayed Mohammed Ishtiaq ");
        UserPageIshtiaqPanel.add(Name2);
        Name2.setBounds(280, 80, 260, 20);

        Mobile2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile2.setText("Mobile: 01945452133");
        UserPageIshtiaqPanel.add(Mobile2);
        Mobile2.setBounds(280, 110, 210, 20);

        Blood2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood2.setText("Blood: A+ ");
        UserPageIshtiaqPanel.add(Blood2);
        Blood2.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageIshtiaqPanel);
        UserPageIshtiaqPanel.setBounds(0, 180, 600, 320);

        UserPageRhymePanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageRhymePanel.setLayout(null);

        Address.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address.setText("Address: Mushiganj, Dhaka ");
        UserPageRhymePanel.add(Address);
        Address.setBounds(280, 170, 210, 20);

        Name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name.setText("Name: Md. Tasuf Morshed ");
        UserPageRhymePanel.add(Name);
        Name.setBounds(280, 80, 210, 20);

        Mobile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile.setText("Mobile: 01956140407 ");
        UserPageRhymePanel.add(Mobile);
        Mobile.setBounds(280, 110, 210, 20);

        Blood.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood.setText("Blood: B+ ");
        UserPageRhymePanel.add(Blood);
        Blood.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageRhymePanel);
        UserPageRhymePanel.setBounds(0, 180, 600, 320);

        UserPageTilokPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageTilokPanel.setLayout(null);

        Address1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address1.setText("Address: Mushiganj, Dhaka ");
        UserPageTilokPanel.add(Address1);
        Address1.setBounds(280, 170, 210, 20);

        Name1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name1.setText("Name: Assadujjaman Tilok");
        UserPageTilokPanel.add(Name1);
        Name1.setBounds(280, 80, 210, 20);

        Mobile1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile1.setText("Mobile: 01956140407 ");
        UserPageTilokPanel.add(Mobile1);
        Mobile1.setBounds(280, 110, 210, 20);

        Blood1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood1.setText("Blood: B+ ");
        UserPageTilokPanel.add(Blood1);
        Blood1.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageTilokPanel);
        UserPageTilokPanel.setBounds(0, 180, 600, 320);

        UserPageMosarofPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageMosarofPanel.setLayout(null);

        Address3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address3.setText("Address: Mirpur, Dhaka ");
        UserPageMosarofPanel.add(Address3);
        Address3.setBounds(280, 170, 210, 20);

        Name3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name3.setText("Name: Md. Mosarof Korim");
        UserPageMosarofPanel.add(Name3);
        Name3.setBounds(280, 80, 210, 20);

        Mobile3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile3.setText("Mobile: 0198554231");
        UserPageMosarofPanel.add(Mobile3);
        Mobile3.setBounds(280, 110, 210, 20);

        Blood3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood3.setText("Blood: B+ ");
        UserPageMosarofPanel.add(Blood3);
        Blood3.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageMosarofPanel);
        UserPageMosarofPanel.setBounds(0, 180, 600, 320);

        getContentPane().add(UserPage);
        UserPage.setBounds(200, 0, 600, 500);

        MealPage.setBackground(new java.awt.Color(204, 204, 204));
        MealPage.setLayout(null);

        MealPanelUpPanel.setBackground(new java.awt.Color(34, 42, 53));
        MealPanelUpPanel.setEnabled(false);
        MealPanelUpPanel.setLayout(null);

        MealPageName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageName.setForeground(new java.awt.Color(255, 255, 255));
        MealPageName.setText("Name");
        MealPanelUpPanel.add(MealPageName);
        MealPageName.setBounds(60, 30, 50, 20);

        MealPageDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageDate.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDate.setText("Date");
        MealPanelUpPanel.add(MealPageDate);
        MealPageDate.setBounds(370, 30, 50, 20);

        MealPageDateField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPanelUpPanel.add(MealPageDateField);
        MealPageDateField.setBounds(420, 26, 130, 30);

        MealPageNameComboBox.setEditable(true);
        MealPageNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        MealPageNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        MealPageNameComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MealPageNameComboBox.setFocusable(false);
        MealPageNameComboBox.setKeySelectionManager(null);
        MealPageNameComboBox.setLightWeightPopupEnabled(false);
        MealPageNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageNameComboBoxActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageNameComboBox);
        MealPageNameComboBox.setBounds(120, 26, 190, 30);

        MealPageDinner.setBackground(new java.awt.Color(34, 42, 53));
        MealPageDinner.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageDinner.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDinner.setText("Dinner");
        MealPageDinner.setBorder(null);
        MealPageDinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageDinner.setFocusable(false);
        MealPageDinner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageDinner.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageDinner.setIconTextGap(10);
        MealPageDinner.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageDinner.setRequestFocusEnabled(false);
        MealPageDinner.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPanelUpPanel.add(MealPageDinner);
        MealPageDinner.setBounds(450, 70, 140, 30);

        MealPageBreakFast.setBackground(new java.awt.Color(34, 42, 53));
        MealPageBreakFast.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageBreakFast.setForeground(new java.awt.Color(255, 255, 255));
        MealPageBreakFast.setText("Break Fast");
        MealPageBreakFast.setBorder(null);
        MealPageBreakFast.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageBreakFast.setFocusPainted(false);
        MealPageBreakFast.setFocusable(false);
        MealPageBreakFast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageBreakFast.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageBreakFast.setIconTextGap(10);
        MealPageBreakFast.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageBreakFast.setRequestFocusEnabled(false);
        MealPageBreakFast.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPageBreakFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageBreakFastActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageBreakFast);
        MealPageBreakFast.setBounds(80, 70, 140, 30);

        MealPageLunch.setBackground(new java.awt.Color(34, 42, 53));
        MealPageLunch.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageLunch.setForeground(new java.awt.Color(255, 255, 255));
        MealPageLunch.setText("Lunch");
        MealPageLunch.setBorder(null);
        MealPageLunch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageLunch.setFocusable(false);
        MealPageLunch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageLunch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageLunch.setIconTextGap(10);
        MealPageLunch.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageLunch.setRequestFocusEnabled(false);
        MealPageLunch.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPageLunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageLunchActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageLunch);
        MealPageLunch.setBounds(280, 70, 140, 30);

        MealPageEditButton.setBackground(new java.awt.Color(12, 15, 18));
        MealPageEditButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageEditButton.setForeground(new java.awt.Color(255, 255, 255));
        MealPageEditButton.setText("Delet");
        MealPageEditButton.setActionCommand("");
        MealPageEditButton.setBorder(null);
        MealPageEditButton.setBorderPainted(false);
        MealPageEditButton.setFocusPainted(false);
        MealPageEditButton.setFocusTraversalPolicyProvider(true);
        MealPageEditButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageEditButton.setIconTextGap(0);
        MealPageEditButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageEditButtonActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageEditButton);
        MealPageEditButton.setBounds(320, 110, 100, 30);

        MealPageSubmitButton.setBackground(new java.awt.Color(12, 15, 18));
        MealPageSubmitButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        MealPageSubmitButton.setText("Sumit");
        MealPageSubmitButton.setActionCommand("");
        MealPageSubmitButton.setBorder(null);
        MealPageSubmitButton.setBorderPainted(false);
        MealPageSubmitButton.setFocusPainted(false);
        MealPageSubmitButton.setFocusable(false);
        MealPageSubmitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageSubmitButton.setIconTextGap(0);
        MealPageSubmitButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageSubmitButtonActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageSubmitButton);
        MealPageSubmitButton.setBounds(180, 110, 100, 30);

        MealPage.add(MealPanelUpPanel);
        MealPanelUpPanel.setBounds(200, 60, 600, 150);

        MealPanelDownPanel.setBackground(new java.awt.Color(204, 204, 204));
        MealPanelDownPanel.setLayout(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(model);
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        MealPanelDownPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 550, 160);

        MealPage.add(MealPanelDownPanel);
        MealPanelDownPanel.setBounds(200, 210, 600, 290);

        getContentPane().add(MealPage);
        MealPage.setBounds(0, 0, 800, 500);

        BazarPage.setBackground(new java.awt.Color(204, 204, 204));
        BazarPage.setEnabled(false);
        BazarPage.setLayout(null);

        MealPanelUpPanel1.setBackground(new java.awt.Color(29, 50, 89));
        MealPanelUpPanel1.setEnabled(false);
        MealPanelUpPanel1.setLayout(null);

        MealPageName1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageName1.setForeground(new java.awt.Color(255, 255, 255));
        MealPageName1.setText("Name");
        MealPanelUpPanel1.add(MealPageName1);
        MealPageName1.setBounds(60, 30, 50, 20);

        MealPageDate1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageDate1.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDate1.setText("Date");
        MealPanelUpPanel1.add(MealPageDate1);
        MealPageDate1.setBounds(370, 30, 50, 20);

        MealPageDateField1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPanelUpPanel1.add(MealPageDateField1);
        MealPageDateField1.setBounds(420, 26, 130, 30);

        MealPageNameComboBox1.setEditable(true);
        MealPageNameComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        MealPageNameComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        MealPageNameComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MealPageNameComboBox1.setFocusable(false);
        MealPageNameComboBox1.setKeySelectionManager(null);
        MealPageNameComboBox1.setLightWeightPopupEnabled(false);
        MealPageNameComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageNameComboBox1ActionPerformed(evt);
            }
        });
        MealPanelUpPanel1.add(MealPageNameComboBox1);
        MealPageNameComboBox1.setBounds(120, 26, 190, 30);

        MealPageEditButton1.setBackground(new java.awt.Color(29, 50, 89));
        MealPageEditButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageEditButton1.setForeground(new java.awt.Color(255, 255, 255));
        MealPageEditButton1.setText("Delet");
        MealPageEditButton1.setActionCommand("");
        MealPageEditButton1.setBorder(null);
        MealPageEditButton1.setBorderPainted(false);
        MealPageEditButton1.setFocusPainted(false);
        MealPageEditButton1.setFocusTraversalPolicyProvider(true);
        MealPageEditButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageEditButton1.setIconTextGap(0);
        MealPageEditButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageEditButton1ActionPerformed(evt);
            }
        });
        MealPanelUpPanel1.add(MealPageEditButton1);
        MealPageEditButton1.setBounds(320, 130, 100, 30);

        MealPageSubmitButton1.setBackground(new java.awt.Color(29, 50, 89));
        MealPageSubmitButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageSubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        MealPageSubmitButton1.setText("Sumit");
        MealPageSubmitButton1.setActionCommand("");
        MealPageSubmitButton1.setBorder(null);
        MealPageSubmitButton1.setBorderPainted(false);
        MealPageSubmitButton1.setFocusPainted(false);
        MealPageSubmitButton1.setFocusable(false);
        MealPageSubmitButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageSubmitButton1.setIconTextGap(0);
        MealPageSubmitButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageSubmitButton1ActionPerformed(evt);
            }
        });
        MealPanelUpPanel1.add(MealPageSubmitButton1);
        MealPageSubmitButton1.setBounds(170, 130, 100, 30);

        MealPageDate2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageDate2.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDate2.setText("Amount");
        MealPanelUpPanel1.add(MealPageDate2);
        MealPageDate2.setBounds(350, 90, 60, 20);

        MealPageDateField2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageDateField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageDateField2ActionPerformed(evt);
            }
        });
        MealPanelUpPanel1.add(MealPageDateField2);
        MealPageDateField2.setBounds(420, 80, 130, 30);

        MealPageDate3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageDate3.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDate3.setText("Item");
        MealPanelUpPanel1.add(MealPageDate3);
        MealPageDate3.setBounds(60, 90, 60, 20);

        MealPageDateField3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageDateField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageDateField3ActionPerformed(evt);
            }
        });
        MealPanelUpPanel1.add(MealPageDateField3);
        MealPageDateField3.setBounds(120, 80, 190, 30);

        BazarPage.add(MealPanelUpPanel1);
        MealPanelUpPanel1.setBounds(200, 60, 600, 170);

        MealPanelDownPanel1.setBackground(new java.awt.Color(204, 204, 204));
        MealPanelDownPanel1.setLayout(null);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable2.setModel(modelforBazar);
        jTable2.setFocusable(false);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setOpaque(false);
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowGrid(false);
        jScrollPane2.setViewportView(jTable2);

        MealPanelDownPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 550, 160);

        BazarPage.add(MealPanelDownPanel1);
        MealPanelDownPanel1.setBounds(200, 210, 600, 290);

        getContentPane().add(BazarPage);
        BazarPage.setBounds(0, 0, 800, 500);

        BillPage.setBackground(new java.awt.Color(0, 255, 204));
        BillPage.setEnabled(false);
        BillPage.setLayout(null);
        getContentPane().add(BillPage);
        BillPage.setBounds(0, 0, 800, 500);

        AmountPage.setBackground(new java.awt.Color(51, 0, 51));
        AmountPage.setEnabled(false);
        AmountPage.setLayout(null);
        getContentPane().add(AmountPage);
        AmountPage.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainLeftPanelOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelOptionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainLeftPanelOptionButtonActionPerformed

    private void MainLeftPanelMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelMealButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(true);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelMealButtonActionPerformed

    private void MainLeftPanelBazarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelBazarButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(true);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelBazarButtonActionPerformed

    private void MainLeftPanelBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelBillButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(true);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelBillButtonActionPerformed

    private void MainLeftPanelAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelAmountButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(true);
    }//GEN-LAST:event_MainLeftPanelAmountButtonActionPerformed

    private void MainLeftPanelUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelUserButtonActionPerformed
        UserPage.setVisible(true);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelUserButtonActionPerformed

    private void TaslufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaslufActionPerformed
        UserPageRhymePanel.setVisible(true);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(false);
    }//GEN-LAST:event_TaslufActionPerformed

    private void TilokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TilokActionPerformed
        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(true);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(false);
    }//GEN-LAST:event_TilokActionPerformed

    private void MosarofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosarofActionPerformed
        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(true);
    }//GEN-LAST:event_MosarofActionPerformed

    private void IshtiaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IshtiaqActionPerformed

        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(true);
        UserPageMosarofPanel.setVisible(false);

    }//GEN-LAST:event_IshtiaqActionPerformed

    private void MealPageNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageNameComboBoxActionPerformed
           
    }//GEN-LAST:event_MealPageNameComboBoxActionPerformed

    private void MealPageBreakFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageBreakFastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageBreakFastActionPerformed

    private void MealPageLunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageLunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageLunchActionPerformed

    private void MealPageSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageSubmitButtonActionPerformed
        if(evt.getSource() == MealPageSubmitButton)
        {
            int bf = 0;
            int l = 0;
            int d = 0;
            row[0] = this.MealPageNameComboBox.getSelectedItem().toString();
            if(this.MealPageBreakFast.isSelected())
            {
                bf = 1;
            }
            row[1] = Integer.toString(bf);
            if(this.MealPageLunch.isSelected())
            {
                l = 1;
            }
            row[2] = Integer.toString(l);
            if(this.MealPageDinner.isSelected())
            {
                d = 1;
            }
            row[3] = Integer.toString(d);
            row[4] = Integer.toString(bf+l+d);
            row[5] = this.MealPageDateField.getText();
            model.addRow(row);
        }
        
    }//GEN-LAST:event_MealPageSubmitButtonActionPerformed

    private void MealPageEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageEditButtonActionPerformed
        int numerOfRow = this.jTable1.getSelectedRow();
        if(numerOfRow >= 0)
        {
            model.removeRow(numerOfRow);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row has been selected or no row exists");
        }
    }//GEN-LAST:event_MealPageEditButtonActionPerformed

    private void MealPageNameComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageNameComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageNameComboBox1ActionPerformed

    private void MealPageEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageEditButton1ActionPerformed
        int numerOfRow = this.jTable2.getSelectedRow();
        if(numerOfRow >= 0)
        {
            modelforBazar.removeRow(numerOfRow);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row has been selected or no row exists");
        }
    }//GEN-LAST:event_MealPageEditButton1ActionPerformed

    private void MealPageSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageSubmitButton1ActionPerformed
        rowForBazar[0] = this.MealPageNameComboBox1.getSelectedItem().toString();
        rowForBazar[1] = this.MealPageDateField3.getText();
        rowForBazar[2] = this.MealPageDateField2.getText();
        rowForBazar[3] = this.MealPageDateField1.getText();
        modelforBazar.addRow(rowForBazar);
    }//GEN-LAST:event_MealPageSubmitButton1ActionPerformed

    private void MealPageDateField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageDateField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageDateField2ActionPerformed

    private void MealPageDateField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageDateField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageDateField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Address3;
    private javax.swing.JPanel AmountPage;
    private javax.swing.JPanel BazarPage;
    private javax.swing.JPanel BillPage;
    private javax.swing.JLabel Blood;
    private javax.swing.JLabel Blood1;
    private javax.swing.JLabel Blood2;
    private javax.swing.JLabel Blood3;
    private javax.swing.JButton Ishtiaq;
    private javax.swing.JPanel MainLeftPanel;
    private javax.swing.JButton MainLeftPanelAmountButton;
    private javax.swing.JLabel MainLeftPanelAmountIcon;
    private javax.swing.JButton MainLeftPanelBazarButton;
    private javax.swing.JLabel MainLeftPanelBazarIcon;
    private javax.swing.JButton MainLeftPanelBillButton;
    private javax.swing.JLabel MainLeftPanelBillIcon;
    private javax.swing.JButton MainLeftPanelMealButton;
    private javax.swing.JLabel MainLeftPanelMealIcon;
    private javax.swing.JButton MainLeftPanelOptionButton;
    private javax.swing.JLabel MainLeftPanelOptionIcon;
    private javax.swing.JButton MainLeftPanelUserButton;
    private javax.swing.JLabel MainLeftPanelUserIcon;
    private javax.swing.JPanel MealPage;
    private javax.swing.JCheckBox MealPageBreakFast;
    private javax.swing.JLabel MealPageDate;
    private javax.swing.JLabel MealPageDate1;
    private javax.swing.JLabel MealPageDate2;
    private javax.swing.JLabel MealPageDate3;
    private javax.swing.JTextField MealPageDateField;
    private javax.swing.JTextField MealPageDateField1;
    private javax.swing.JTextField MealPageDateField2;
    private javax.swing.JTextField MealPageDateField3;
    private javax.swing.JCheckBox MealPageDinner;
    private javax.swing.JButton MealPageEditButton;
    private javax.swing.JButton MealPageEditButton1;
    private javax.swing.JCheckBox MealPageLunch;
    private javax.swing.JLabel MealPageName;
    private javax.swing.JLabel MealPageName1;
    private javax.swing.JComboBox<String> MealPageNameComboBox;
    private javax.swing.JComboBox<String> MealPageNameComboBox1;
    private javax.swing.JButton MealPageSubmitButton;
    private javax.swing.JButton MealPageSubmitButton1;
    private javax.swing.JPanel MealPanelDownPanel;
    private javax.swing.JPanel MealPanelDownPanel1;
    private javax.swing.JPanel MealPanelUpPanel;
    private javax.swing.JPanel MealPanelUpPanel1;
    private javax.swing.JLabel Mobile;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JLabel Mobile2;
    private javax.swing.JLabel Mobile3;
    private javax.swing.JButton Mosarof;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JButton Tasluf;
    private javax.swing.JButton Tilok;
    private javax.swing.JLabel User;
    private javax.swing.JLabel User2;
    private javax.swing.JLabel User3;
    private javax.swing.JLabel User4;
    private javax.swing.JPanel UserPage;
    private javax.swing.JPanel UserPageIshtiaqPanel;
    private javax.swing.JPanel UserPageMosarofPanel;
    private javax.swing.JPanel UserPageRhymePanel;
    private javax.swing.JPanel UserPageTilokPanel;
    private javax.swing.JPanel UserPageUpPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
