/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectwithswing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon; 
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author User
 */
public class pages extends javax.swing.JFrame {
    public DefaultTableModel model,modelforBazar,modelforBill;
    public String[] com = {"Name","Break Fast","Lunch","Diner","Total Meal","Date"};
    public String[] comForBazar = {"                Name","                Item","              Amount","                Date"};
    public String[] comForBill = {"                Name","                Bill","              Amount","                Date"};
    public String[] row = new String[6]; 
    public String[] rowForBazar = new String[4]; 
    public String[] rowForBill = new String[4]; 
    public String[] name = {"Md Tasluf Morsehed","Assadijjaman Tilok","Sayed Mohammed Ishtiaq","Md. Mosarof Korim","Relatives"};
    public pages() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(com);
        
        modelforBazar = new DefaultTableModel();
        modelforBazar.setColumnIdentifiers(comForBazar);
        
        modelforBill = new DefaultTableModel();
        modelforBill.setColumnIdentifiers(comForBill);
        
        initComponents();
        this.setSize(800,500);
        this.setLocationRelativeTo(null);
        
        this.UserPage.setVisible(true);
        this.MealPage.setVisible(false);
        this.BazarPage.setVisible(false);
        this.BillPage.setVisible(false);
        this.AmountPage.setVisible(false);
        
       
        
    }
    public ImageIcon IconScale(String s)
    {
        ImageIcon icon = new ImageIcon("src/img/"+s);
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(27,27, Image.SCALE_SMOOTH);
        icon = new ImageIcon(newImage);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLeftPanel = new javax.swing.JPanel();
        MainLeftPanelUserIcon = new javax.swing.JLabel();
        MainLeftPanelMealIcon = new javax.swing.JLabel();
        MainLeftPanelBazarIcon = new javax.swing.JLabel();
        MainLeftPanelBillIcon = new javax.swing.JLabel();
        MainLeftPanelAmountIcon = new javax.swing.JLabel();
        MainLeftPanelOptionIcon = new javax.swing.JLabel();
        MainLeftPanelUserButton = new javax.swing.JButton();
        MainLeftPanelMealButton = new javax.swing.JButton();
        MainLeftPanelBazarButton = new javax.swing.JButton();
        MainLeftPanelBillButton = new javax.swing.JButton();
        MainLeftPanelAmountButton = new javax.swing.JButton();
        MainLeftPanelOptionButton = new javax.swing.JButton();
        AmountPage = new javax.swing.JPanel();
        AmountPageUpPanel1 = new javax.swing.JPanel();
        User1 = new javax.swing.JLabel();
        User5 = new javax.swing.JLabel();
        User6 = new javax.swing.JLabel();
        User7 = new javax.swing.JLabel();
        Ishtiaq1 = new javax.swing.JButton();
        Tasluf1 = new javax.swing.JButton();
        Tilok1 = new javax.swing.JButton();
        Mosarof1 = new javax.swing.JButton();
        AmountPageDownPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        UserPage = new javax.swing.JPanel();
        UserPageUpPanel = new javax.swing.JPanel();
        User = new javax.swing.JLabel();
        User2 = new javax.swing.JLabel();
        User3 = new javax.swing.JLabel();
        User4 = new javax.swing.JLabel();
        Ishtiaq = new javax.swing.JButton();
        Tasluf = new javax.swing.JButton();
        Tilok = new javax.swing.JButton();
        Mosarof = new javax.swing.JButton();
        UserPageIshtiaqPanel = new javax.swing.JPanel();
        Address2 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Mobile2 = new javax.swing.JLabel();
        Blood2 = new javax.swing.JLabel();
        UserPageRhymePanel = new javax.swing.JPanel();
        Address = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Mobile = new javax.swing.JLabel();
        Blood = new javax.swing.JLabel();
        UserPageTilokPanel = new javax.swing.JPanel();
        Address1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Mobile1 = new javax.swing.JLabel();
        Blood1 = new javax.swing.JLabel();
        UserPageMosarofPanel = new javax.swing.JPanel();
        Address3 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Mobile3 = new javax.swing.JLabel();
        Blood3 = new javax.swing.JLabel();
        MealPage = new javax.swing.JPanel();
        MealPanelUpPanel = new javax.swing.JPanel();
        MealPageName = new javax.swing.JLabel();
        MealPageDate = new javax.swing.JLabel();
        MealPageDateField = new javax.swing.JTextField();
        MealPageNameComboBox = new javax.swing.JComboBox<>();
        MealPageDinner = new javax.swing.JCheckBox();
        MealPageBreakFast = new javax.swing.JCheckBox();
        MealPageLunch = new javax.swing.JCheckBox();
        MealPageEditButton = new javax.swing.JButton();
        MealPageSubmitButton = new javax.swing.JButton();
        MealPanelDownPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BazarPage = new javax.swing.JPanel();
        BazarPanelUpPanel1 = new javax.swing.JPanel();
        BazarPageName1 = new javax.swing.JLabel();
        BazarPageDate1 = new javax.swing.JLabel();
        BazarPageDateField1 = new javax.swing.JTextField();
        BazarPageNameComboBox1 = new javax.swing.JComboBox<>();
        BazarPageEditButton1 = new javax.swing.JButton();
        BazarPageSubmitButton1 = new javax.swing.JButton();
        BazarPageAmount = new javax.swing.JLabel();
        BazarPageAmountField = new javax.swing.JTextField();
        BazarPageItem = new javax.swing.JLabel();
        BazarPageItemField = new javax.swing.JTextField();
        BazarDownPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BillPage = new javax.swing.JPanel();
        BillPanelUpPanel2 = new javax.swing.JPanel();
        BazarPageName2 = new javax.swing.JLabel();
        BazarPageDate2 = new javax.swing.JLabel();
        BazarPageDateField2 = new javax.swing.JTextField();
        BazarPageNameComboBox2 = new javax.swing.JComboBox<>();
        BazarPageEditButton2 = new javax.swing.JButton();
        BazarPageSubmitButton2 = new javax.swing.JButton();
        BazarPageAmount1 = new javax.swing.JLabel();
        BazarPageAmountField1 = new javax.swing.JTextField();
        BazarPageItem1 = new javax.swing.JLabel();
        BazarPageItemField1 = new javax.swing.JTextField();
        BillDownPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MainLeftPanel.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanel.setLayout(null);

        MainLeftPanelUserIcon.setBackground(new java.awt.Color(255, 255, 255));
        MainLeftPanelUserIcon.setIcon(IconScale("2703063-512.png"));
        MainLeftPanel.add(MainLeftPanelUserIcon);
        MainLeftPanelUserIcon.setBounds(40, 60, 27, 27);

        MainLeftPanelMealIcon.setIcon(IconScale("meal.png"));
        MainLeftPanel.add(MainLeftPanelMealIcon);
        MainLeftPanelMealIcon.setBounds(40, 120, 27, 27);

        MainLeftPanelBazarIcon.setIcon(IconScale("bazar.png"));
        MainLeftPanel.add(MainLeftPanelBazarIcon);
        MainLeftPanelBazarIcon.setBounds(40, 180, 27, 27);

        MainLeftPanelBillIcon.setIcon(IconScale("bill.png"));
        MainLeftPanel.add(MainLeftPanelBillIcon);
        MainLeftPanelBillIcon.setBounds(40, 240, 27, 27);

        MainLeftPanelAmountIcon.setIcon(IconScale("amount.png"));
        MainLeftPanel.add(MainLeftPanelAmountIcon);
        MainLeftPanelAmountIcon.setBounds(40, 300, 27, 27);

        MainLeftPanelOptionIcon.setIcon(IconScale("option.png"));
        MainLeftPanel.add(MainLeftPanelOptionIcon);
        MainLeftPanelOptionIcon.setBounds(40, 360, 27, 27);

        MainLeftPanelUserButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelUserButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelUserButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelUserButton.setText("User");
        MainLeftPanelUserButton.setAlignmentY(1.0F);
        MainLeftPanelUserButton.setBorder(null);
        MainLeftPanelUserButton.setBorderPainted(false);
        MainLeftPanelUserButton.setContentAreaFilled(false);
        MainLeftPanelUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelUserButton.setFocusable(false);
        MainLeftPanelUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelUserButton.setIconTextGap(0);
        MainLeftPanelUserButton.setRequestFocusEnabled(false);
        MainLeftPanelUserButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelUserButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelUserButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelUserButton);
        MainLeftPanelUserButton.setBounds(80, 60, 80, 30);

        MainLeftPanelMealButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelMealButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelMealButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelMealButton.setText("Meal");
        MainLeftPanelMealButton.setAlignmentY(1.0F);
        MainLeftPanelMealButton.setBorder(null);
        MainLeftPanelMealButton.setBorderPainted(false);
        MainLeftPanelMealButton.setContentAreaFilled(false);
        MainLeftPanelMealButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelMealButton.setFocusable(false);
        MainLeftPanelMealButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelMealButton.setIconTextGap(0);
        MainLeftPanelMealButton.setRequestFocusEnabled(false);
        MainLeftPanelMealButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelMealButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelMealButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelMealButton);
        MainLeftPanelMealButton.setBounds(80, 120, 80, 30);

        MainLeftPanelBazarButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelBazarButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelBazarButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelBazarButton.setText("Bazar");
        MainLeftPanelBazarButton.setAlignmentY(1.0F);
        MainLeftPanelBazarButton.setBorder(null);
        MainLeftPanelBazarButton.setBorderPainted(false);
        MainLeftPanelBazarButton.setContentAreaFilled(false);
        MainLeftPanelBazarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelBazarButton.setFocusable(false);
        MainLeftPanelBazarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelBazarButton.setIconTextGap(0);
        MainLeftPanelBazarButton.setRequestFocusEnabled(false);
        MainLeftPanelBazarButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelBazarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelBazarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelBazarButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelBazarButton);
        MainLeftPanelBazarButton.setBounds(80, 180, 80, 30);

        MainLeftPanelBillButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelBillButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelBillButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelBillButton.setText("Bill");
        MainLeftPanelBillButton.setAlignmentY(1.0F);
        MainLeftPanelBillButton.setBorder(null);
        MainLeftPanelBillButton.setBorderPainted(false);
        MainLeftPanelBillButton.setContentAreaFilled(false);
        MainLeftPanelBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelBillButton.setFocusable(false);
        MainLeftPanelBillButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelBillButton.setIconTextGap(0);
        MainLeftPanelBillButton.setRequestFocusEnabled(false);
        MainLeftPanelBillButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelBillButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelBillButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelBillButton);
        MainLeftPanelBillButton.setBounds(80, 240, 80, 30);

        MainLeftPanelAmountButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelAmountButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelAmountButton.setText("Amount");
        MainLeftPanelAmountButton.setAlignmentY(1.0F);
        MainLeftPanelAmountButton.setBorder(null);
        MainLeftPanelAmountButton.setBorderPainted(false);
        MainLeftPanelAmountButton.setContentAreaFilled(false);
        MainLeftPanelAmountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelAmountButton.setFocusable(false);
        MainLeftPanelAmountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelAmountButton.setIconTextGap(0);
        MainLeftPanelAmountButton.setRequestFocusEnabled(false);
        MainLeftPanelAmountButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelAmountButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelAmountButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelAmountButton);
        MainLeftPanelAmountButton.setBounds(80, 300, 80, 30);

        MainLeftPanelOptionButton.setBackground(new java.awt.Color(43, 30, 72));
        MainLeftPanelOptionButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MainLeftPanelOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        MainLeftPanelOptionButton.setText("Option");
        MainLeftPanelOptionButton.setAlignmentY(1.0F);
        MainLeftPanelOptionButton.setBorder(null);
        MainLeftPanelOptionButton.setBorderPainted(false);
        MainLeftPanelOptionButton.setContentAreaFilled(false);
        MainLeftPanelOptionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainLeftPanelOptionButton.setFocusable(false);
        MainLeftPanelOptionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MainLeftPanelOptionButton.setIconTextGap(0);
        MainLeftPanelOptionButton.setRequestFocusEnabled(false);
        MainLeftPanelOptionButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        MainLeftPanelOptionButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MainLeftPanelOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainLeftPanelOptionButtonActionPerformed(evt);
            }
        });
        MainLeftPanel.add(MainLeftPanelOptionButton);
        MainLeftPanelOptionButton.setBounds(80, 360, 80, 30);

        getContentPane().add(MainLeftPanel);
        MainLeftPanel.setBounds(0, 0, 200, 500);

        AmountPage.setBackground(new java.awt.Color(204, 204, 204));
        AmountPage.setEnabled(false);
        AmountPage.setLayout(null);

        AmountPageUpPanel1.setBackground(new java.awt.Color(24, 23, 23));
        AmountPageUpPanel1.setLayout(null);

        User1.setBackground(new java.awt.Color(255, 255, 255));
        User1.setIcon(IconScale("2703063-512.png"));
        AmountPageUpPanel1.add(User1);
        User1.setBounds(80, 20, 27, 27);

        User5.setBackground(new java.awt.Color(255, 255, 255));
        User5.setIcon(IconScale("2703063-512.png"));
        AmountPageUpPanel1.add(User5);
        User5.setBounds(80, 70, 27, 27);

        User6.setBackground(new java.awt.Color(255, 255, 255));
        User6.setIcon(IconScale("2703063-512.png"));
        AmountPageUpPanel1.add(User6);
        User6.setBounds(350, 20, 27, 27);

        User7.setBackground(new java.awt.Color(255, 255, 255));
        User7.setIcon(IconScale("2703063-512.png"));
        AmountPageUpPanel1.add(User7);
        User7.setBounds(350, 70, 27, 27);

        Ishtiaq1.setBackground(new java.awt.Color(43, 30, 72));
        Ishtiaq1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Ishtiaq1.setForeground(new java.awt.Color(255, 255, 255));
        Ishtiaq1.setText("Sayed Mohammed Ishtiaq");
        Ishtiaq1.setAlignmentY(1.0F);
        Ishtiaq1.setBorder(null);
        Ishtiaq1.setBorderPainted(false);
        Ishtiaq1.setContentAreaFilled(false);
        Ishtiaq1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ishtiaq1.setFocusable(false);
        Ishtiaq1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ishtiaq1.setIconTextGap(0);
        Ishtiaq1.setRequestFocusEnabled(false);
        Ishtiaq1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Ishtiaq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ishtiaq1ActionPerformed(evt);
            }
        });
        AmountPageUpPanel1.add(Ishtiaq1);
        Ishtiaq1.setBounds(120, 70, 200, 30);

        Tasluf1.setBackground(new java.awt.Color(43, 30, 72));
        Tasluf1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tasluf1.setForeground(new java.awt.Color(255, 255, 255));
        Tasluf1.setText("Md. Tasluf Morshed");
        Tasluf1.setAlignmentY(1.0F);
        Tasluf1.setBorder(null);
        Tasluf1.setBorderPainted(false);
        Tasluf1.setContentAreaFilled(false);
        Tasluf1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tasluf1.setFocusable(false);
        Tasluf1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tasluf1.setIconTextGap(0);
        Tasluf1.setRequestFocusEnabled(false);
        Tasluf1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tasluf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tasluf1ActionPerformed(evt);
            }
        });
        AmountPageUpPanel1.add(Tasluf1);
        Tasluf1.setBounds(120, 20, 160, 30);

        Tilok1.setBackground(new java.awt.Color(43, 30, 72));
        Tilok1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tilok1.setForeground(new java.awt.Color(255, 255, 255));
        Tilok1.setAlignmentY(1.0F);
        Tilok1.setBorder(null);
        Tilok1.setBorderPainted(false);
        Tilok1.setContentAreaFilled(false);
        Tilok1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tilok1.setFocusable(false);
        Tilok1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tilok1.setIconTextGap(0);
        Tilok1.setLabel("Assadujjman Tilok");
        Tilok1.setRequestFocusEnabled(false);
        Tilok1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tilok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tilok1ActionPerformed(evt);
            }
        });
        AmountPageUpPanel1.add(Tilok1);
        Tilok1.setBounds(390, 20, 160, 30);

        Mosarof1.setBackground(new java.awt.Color(43, 30, 72));
        Mosarof1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mosarof1.setForeground(new java.awt.Color(255, 255, 255));
        Mosarof1.setText("Md. Mosarof Korim");
        Mosarof1.setAlignmentY(1.0F);
        Mosarof1.setBorder(null);
        Mosarof1.setBorderPainted(false);
        Mosarof1.setContentAreaFilled(false);
        Mosarof1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mosarof1.setFocusable(false);
        Mosarof1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mosarof1.setIconTextGap(0);
        Mosarof1.setRequestFocusEnabled(false);
        Mosarof1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Mosarof1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mosarof1ActionPerformed(evt);
            }
        });
        AmountPageUpPanel1.add(Mosarof1);
        Mosarof1.setBounds(390, 70, 160, 30);

        AmountPage.add(AmountPageUpPanel1);
        AmountPageUpPanel1.setBounds(0, 60, 600, 120);

        AmountPageDownPanel.setBackground(new java.awt.Color(204, 204, 204));
        AmountPageDownPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        AmountPageDownPanel.add(jPanel1);
        jPanel1.setBounds(40, 60, 130, 110);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("    1000");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(0);
        jLabel2.setOpaque(true);
        jLabel2.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel2);
        jLabel2.setBounds(290, 60, 70, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Liabilities");
        AmountPageDownPanel.add(jLabel3);
        jLabel3.setBounds(210, 150, 70, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Total Meal");
        AmountPageDownPanel.add(jLabel4);
        jLabel4.setBounds(30, 220, 80, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Total Bazar");
        AmountPageDownPanel.add(jLabel5);
        jLabel5.setBounds(220, 220, 90, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("    1000");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(0);
        jLabel6.setOpaque(true);
        jLabel6.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel6);
        jLabel6.setBounds(310, 210, 70, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Total Bill");
        AmountPageDownPanel.add(jLabel7);
        jLabel7.setBounds(420, 220, 70, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("    1000");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setIconTextGap(0);
        jLabel8.setOpaque(true);
        jLabel8.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel8);
        jLabel8.setBounds(490, 210, 70, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Meal");
        AmountPageDownPanel.add(jLabel9);
        jLabel9.setBounds(210, 70, 40, 20);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Spend");
        AmountPageDownPanel.add(jLabel10);
        jLabel10.setBounds(210, 110, 50, 20);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("    1000");
        jLabel11.setToolTipText("");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setIconTextGap(0);
        jLabel11.setOpaque(true);
        jLabel11.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel11);
        jLabel11.setBounds(120, 210, 70, 40);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("    1000");
        jLabel12.setToolTipText("");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(0);
        jLabel12.setOpaque(true);
        jLabel12.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel12);
        jLabel12.setBounds(290, 140, 70, 30);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("    1000");
        jLabel13.setToolTipText("");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(0);
        jLabel13.setOpaque(true);
        jLabel13.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel13);
        jLabel13.setBounds(290, 100, 70, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setText("Bazar");
        AmountPageDownPanel.add(jLabel14);
        jLabel14.setBounds(400, 70, 50, 20);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setText("    1000");
        jLabel15.setToolTipText("");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setIconTextGap(0);
        jLabel15.setOpaque(true);
        jLabel15.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel15);
        jLabel15.setBounds(490, 60, 70, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setText("    1000");
        jLabel16.setToolTipText("");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setIconTextGap(0);
        jLabel16.setOpaque(true);
        jLabel16.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel16);
        jLabel16.setBounds(490, 100, 70, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setText("Bill");
        AmountPageDownPanel.add(jLabel17);
        jLabel17.setBounds(400, 110, 50, 20);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel18.setText("Receivable");
        AmountPageDownPanel.add(jLabel18);
        jLabel18.setBounds(400, 150, 90, 20);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setText("    1000");
        jLabel19.setToolTipText("");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setIconTextGap(0);
        jLabel19.setOpaque(true);
        jLabel19.setRequestFocusEnabled(false);
        AmountPageDownPanel.add(jLabel19);
        jLabel19.setBounds(490, 140, 70, 30);

        AmountPage.add(AmountPageDownPanel);
        AmountPageDownPanel.setBounds(0, 180, 600, 320);

        getContentPane().add(AmountPage);
        AmountPage.setBounds(200, 0, 600, 500);

        UserPage.setBackground(new java.awt.Color(204, 204, 204));
        UserPage.setAlignmentX(0.0F);
        UserPage.setFocusable(false);
        UserPage.setLayout(null);

        UserPageUpPanel.setBackground(new java.awt.Color(67, 47, 125));
        UserPageUpPanel.setLayout(null);

        User.setBackground(new java.awt.Color(255, 255, 255));
        User.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User);
        User.setBounds(80, 20, 27, 27);

        User2.setBackground(new java.awt.Color(255, 255, 255));
        User2.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User2);
        User2.setBounds(80, 70, 27, 27);

        User3.setBackground(new java.awt.Color(255, 255, 255));
        User3.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User3);
        User3.setBounds(350, 20, 27, 27);

        User4.setBackground(new java.awt.Color(255, 255, 255));
        User4.setIcon(IconScale("2703063-512.png"));
        UserPageUpPanel.add(User4);
        User4.setBounds(350, 70, 27, 27);

        Ishtiaq.setBackground(new java.awt.Color(43, 30, 72));
        Ishtiaq.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Ishtiaq.setForeground(new java.awt.Color(255, 255, 255));
        Ishtiaq.setText("Sayed Mohammed Ishtiaq");
        Ishtiaq.setAlignmentY(1.0F);
        Ishtiaq.setBorder(null);
        Ishtiaq.setBorderPainted(false);
        Ishtiaq.setContentAreaFilled(false);
        Ishtiaq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ishtiaq.setFocusable(false);
        Ishtiaq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ishtiaq.setIconTextGap(0);
        Ishtiaq.setRequestFocusEnabled(false);
        Ishtiaq.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Ishtiaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IshtiaqActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Ishtiaq);
        Ishtiaq.setBounds(120, 70, 200, 30);

        Tasluf.setBackground(new java.awt.Color(43, 30, 72));
        Tasluf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tasluf.setForeground(new java.awt.Color(255, 255, 255));
        Tasluf.setText("Md. Tasluf Morshed");
        Tasluf.setAlignmentY(1.0F);
        Tasluf.setBorder(null);
        Tasluf.setBorderPainted(false);
        Tasluf.setContentAreaFilled(false);
        Tasluf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tasluf.setFocusable(false);
        Tasluf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tasluf.setIconTextGap(0);
        Tasluf.setRequestFocusEnabled(false);
        Tasluf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tasluf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaslufActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Tasluf);
        Tasluf.setBounds(120, 20, 160, 30);

        Tilok.setBackground(new java.awt.Color(43, 30, 72));
        Tilok.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tilok.setForeground(new java.awt.Color(255, 255, 255));
        Tilok.setAlignmentY(1.0F);
        Tilok.setBorder(null);
        Tilok.setBorderPainted(false);
        Tilok.setContentAreaFilled(false);
        Tilok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tilok.setFocusable(false);
        Tilok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tilok.setIconTextGap(0);
        Tilok.setLabel("Assadujjman Tilok");
        Tilok.setRequestFocusEnabled(false);
        Tilok.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tilok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TilokActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Tilok);
        Tilok.setBounds(390, 20, 160, 30);

        Mosarof.setBackground(new java.awt.Color(43, 30, 72));
        Mosarof.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mosarof.setForeground(new java.awt.Color(255, 255, 255));
        Mosarof.setText("Md. Mosarof Korim");
        Mosarof.setAlignmentY(1.0F);
        Mosarof.setBorder(null);
        Mosarof.setBorderPainted(false);
        Mosarof.setContentAreaFilled(false);
        Mosarof.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mosarof.setFocusable(false);
        Mosarof.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mosarof.setIconTextGap(0);
        Mosarof.setRequestFocusEnabled(false);
        Mosarof.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Mosarof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosarofActionPerformed(evt);
            }
        });
        UserPageUpPanel.add(Mosarof);
        Mosarof.setBounds(390, 70, 160, 30);

        UserPage.add(UserPageUpPanel);
        UserPageUpPanel.setBounds(0, 60, 600, 120);

        UserPageIshtiaqPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageIshtiaqPanel.setLayout(null);

        Address2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address2.setText("Address: Sankor, Dhaka ");
        UserPageIshtiaqPanel.add(Address2);
        Address2.setBounds(280, 170, 210, 20);

        Name2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name2.setText("Name: Sayed Mohammed Ishtiaq ");
        UserPageIshtiaqPanel.add(Name2);
        Name2.setBounds(280, 80, 260, 20);

        Mobile2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile2.setText("Mobile: 01945452133");
        UserPageIshtiaqPanel.add(Mobile2);
        Mobile2.setBounds(280, 110, 210, 20);

        Blood2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood2.setText("Blood: A+ ");
        UserPageIshtiaqPanel.add(Blood2);
        Blood2.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageIshtiaqPanel);
        UserPageIshtiaqPanel.setBounds(0, 180, 600, 320);

        UserPageRhymePanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageRhymePanel.setLayout(null);

        Address.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address.setText("Address: Mushiganj, Dhaka ");
        UserPageRhymePanel.add(Address);
        Address.setBounds(280, 170, 210, 20);

        Name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name.setText("Name: Md. Tasuf Morshed ");
        UserPageRhymePanel.add(Name);
        Name.setBounds(280, 80, 210, 20);

        Mobile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile.setText("Mobile: 01956140407 ");
        UserPageRhymePanel.add(Mobile);
        Mobile.setBounds(280, 110, 210, 20);

        Blood.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood.setText("Blood: B+ ");
        UserPageRhymePanel.add(Blood);
        Blood.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageRhymePanel);
        UserPageRhymePanel.setBounds(0, 180, 600, 320);

        UserPageTilokPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageTilokPanel.setLayout(null);

        Address1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address1.setText("Address: Mushiganj, Dhaka ");
        UserPageTilokPanel.add(Address1);
        Address1.setBounds(280, 170, 210, 20);

        Name1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name1.setText("Name: Assadujjaman Tilok");
        UserPageTilokPanel.add(Name1);
        Name1.setBounds(280, 80, 210, 20);

        Mobile1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile1.setText("Mobile: 01956140407 ");
        UserPageTilokPanel.add(Mobile1);
        Mobile1.setBounds(280, 110, 210, 20);

        Blood1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood1.setText("Blood: B+ ");
        UserPageTilokPanel.add(Blood1);
        Blood1.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageTilokPanel);
        UserPageTilokPanel.setBounds(0, 180, 600, 320);

        UserPageMosarofPanel.setBackground(new java.awt.Color(204, 204, 204));
        UserPageMosarofPanel.setLayout(null);

        Address3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Address3.setText("Address: Mirpur, Dhaka ");
        UserPageMosarofPanel.add(Address3);
        Address3.setBounds(280, 170, 210, 20);

        Name3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name3.setText("Name: Md. Mosarof Korim");
        UserPageMosarofPanel.add(Name3);
        Name3.setBounds(280, 80, 210, 20);

        Mobile3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Mobile3.setText("Mobile: 0198554231");
        UserPageMosarofPanel.add(Mobile3);
        Mobile3.setBounds(280, 110, 210, 20);

        Blood3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Blood3.setText("Blood: B+ ");
        UserPageMosarofPanel.add(Blood3);
        Blood3.setBounds(280, 140, 210, 20);

        UserPage.add(UserPageMosarofPanel);
        UserPageMosarofPanel.setBounds(0, 180, 600, 320);

        getContentPane().add(UserPage);
        UserPage.setBounds(200, 0, 600, 500);

        MealPage.setBackground(new java.awt.Color(204, 204, 204));
        MealPage.setLayout(null);

        MealPanelUpPanel.setBackground(new java.awt.Color(34, 42, 53));
        MealPanelUpPanel.setEnabled(false);
        MealPanelUpPanel.setLayout(null);

        MealPageName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageName.setForeground(new java.awt.Color(255, 255, 255));
        MealPageName.setText("Name");
        MealPanelUpPanel.add(MealPageName);
        MealPageName.setBounds(60, 30, 50, 20);

        MealPageDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        MealPageDate.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDate.setText("Date");
        MealPanelUpPanel.add(MealPageDate);
        MealPageDate.setBounds(370, 30, 50, 20);

        MealPageDateField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPanelUpPanel.add(MealPageDateField);
        MealPageDateField.setBounds(420, 26, 130, 30);

        MealPageNameComboBox.setEditable(true);
        MealPageNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        MealPageNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        MealPageNameComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MealPageNameComboBox.setFocusable(false);
        MealPageNameComboBox.setKeySelectionManager(null);
        MealPageNameComboBox.setLightWeightPopupEnabled(false);
        MealPageNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageNameComboBoxActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageNameComboBox);
        MealPageNameComboBox.setBounds(120, 26, 190, 30);

        MealPageDinner.setBackground(new java.awt.Color(34, 42, 53));
        MealPageDinner.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageDinner.setForeground(new java.awt.Color(255, 255, 255));
        MealPageDinner.setText("Dinner");
        MealPageDinner.setBorder(null);
        MealPageDinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageDinner.setFocusable(false);
        MealPageDinner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageDinner.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageDinner.setIconTextGap(10);
        MealPageDinner.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageDinner.setRequestFocusEnabled(false);
        MealPageDinner.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPanelUpPanel.add(MealPageDinner);
        MealPageDinner.setBounds(450, 70, 140, 30);

        MealPageBreakFast.setBackground(new java.awt.Color(34, 42, 53));
        MealPageBreakFast.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageBreakFast.setForeground(new java.awt.Color(255, 255, 255));
        MealPageBreakFast.setText("Break Fast");
        MealPageBreakFast.setBorder(null);
        MealPageBreakFast.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageBreakFast.setFocusPainted(false);
        MealPageBreakFast.setFocusable(false);
        MealPageBreakFast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageBreakFast.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageBreakFast.setIconTextGap(10);
        MealPageBreakFast.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageBreakFast.setRequestFocusEnabled(false);
        MealPageBreakFast.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPageBreakFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageBreakFastActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageBreakFast);
        MealPageBreakFast.setBounds(80, 70, 140, 30);

        MealPageLunch.setBackground(new java.awt.Color(34, 42, 53));
        MealPageLunch.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageLunch.setForeground(new java.awt.Color(255, 255, 255));
        MealPageLunch.setText("Lunch");
        MealPageLunch.setBorder(null);
        MealPageLunch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MealPageLunch.setFocusable(false);
        MealPageLunch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MealPageLunch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MealPageLunch.setIconTextGap(10);
        MealPageLunch.setMargin(new java.awt.Insets(2, 2, 0, 2));
        MealPageLunch.setRequestFocusEnabled(false);
        MealPageLunch.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MealPageLunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageLunchActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageLunch);
        MealPageLunch.setBounds(280, 70, 140, 30);

        MealPageEditButton.setBackground(new java.awt.Color(12, 15, 18));
        MealPageEditButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageEditButton.setForeground(new java.awt.Color(255, 255, 255));
        MealPageEditButton.setText("Delet");
        MealPageEditButton.setActionCommand("");
        MealPageEditButton.setBorder(null);
        MealPageEditButton.setBorderPainted(false);
        MealPageEditButton.setFocusPainted(false);
        MealPageEditButton.setFocusTraversalPolicyProvider(true);
        MealPageEditButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageEditButton.setIconTextGap(0);
        MealPageEditButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageEditButtonActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageEditButton);
        MealPageEditButton.setBounds(320, 110, 100, 30);

        MealPageSubmitButton.setBackground(new java.awt.Color(12, 15, 18));
        MealPageSubmitButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        MealPageSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        MealPageSubmitButton.setText("Sumit");
        MealPageSubmitButton.setActionCommand("");
        MealPageSubmitButton.setBorder(null);
        MealPageSubmitButton.setBorderPainted(false);
        MealPageSubmitButton.setFocusPainted(false);
        MealPageSubmitButton.setFocusable(false);
        MealPageSubmitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MealPageSubmitButton.setIconTextGap(0);
        MealPageSubmitButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MealPageSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPageSubmitButtonActionPerformed(evt);
            }
        });
        MealPanelUpPanel.add(MealPageSubmitButton);
        MealPageSubmitButton.setBounds(180, 110, 100, 30);

        MealPage.add(MealPanelUpPanel);
        MealPanelUpPanel.setBounds(200, 60, 600, 150);

        MealPanelDownPanel.setBackground(new java.awt.Color(204, 204, 204));
        MealPanelDownPanel.setLayout(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(model);
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        MealPanelDownPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 550, 160);

        MealPage.add(MealPanelDownPanel);
        MealPanelDownPanel.setBounds(200, 210, 600, 290);

        getContentPane().add(MealPage);
        MealPage.setBounds(0, 0, 800, 500);

        BazarPage.setBackground(new java.awt.Color(204, 204, 204));
        BazarPage.setEnabled(false);
        BazarPage.setLayout(null);

        BazarPanelUpPanel1.setBackground(new java.awt.Color(29, 50, 89));
        BazarPanelUpPanel1.setEnabled(false);
        BazarPanelUpPanel1.setLayout(null);

        BazarPageName1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageName1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageName1.setText("Name");
        BazarPanelUpPanel1.add(BazarPageName1);
        BazarPageName1.setBounds(60, 30, 50, 20);

        BazarPageDate1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageDate1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageDate1.setText("Date");
        BazarPanelUpPanel1.add(BazarPageDate1);
        BazarPageDate1.setBounds(370, 30, 50, 20);

        BazarPageDateField1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPanelUpPanel1.add(BazarPageDateField1);
        BazarPageDateField1.setBounds(420, 26, 130, 30);

        BazarPageNameComboBox1.setEditable(true);
        BazarPageNameComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BazarPageNameComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        BazarPageNameComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BazarPageNameComboBox1.setFocusable(false);
        BazarPageNameComboBox1.setKeySelectionManager(null);
        BazarPageNameComboBox1.setLightWeightPopupEnabled(false);
        BazarPageNameComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageNameComboBox1ActionPerformed(evt);
            }
        });
        BazarPanelUpPanel1.add(BazarPageNameComboBox1);
        BazarPageNameComboBox1.setBounds(120, 26, 190, 30);

        BazarPageEditButton1.setBackground(new java.awt.Color(29, 50, 89));
        BazarPageEditButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageEditButton1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageEditButton1.setText("Delet");
        BazarPageEditButton1.setActionCommand("");
        BazarPageEditButton1.setBorder(null);
        BazarPageEditButton1.setBorderPainted(false);
        BazarPageEditButton1.setFocusPainted(false);
        BazarPageEditButton1.setFocusTraversalPolicyProvider(true);
        BazarPageEditButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BazarPageEditButton1.setIconTextGap(0);
        BazarPageEditButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BazarPageEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageEditButton1ActionPerformed(evt);
            }
        });
        BazarPanelUpPanel1.add(BazarPageEditButton1);
        BazarPageEditButton1.setBounds(320, 130, 100, 30);

        BazarPageSubmitButton1.setBackground(new java.awt.Color(29, 50, 89));
        BazarPageSubmitButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageSubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageSubmitButton1.setText("Sumit");
        BazarPageSubmitButton1.setActionCommand("");
        BazarPageSubmitButton1.setBorder(null);
        BazarPageSubmitButton1.setBorderPainted(false);
        BazarPageSubmitButton1.setFocusPainted(false);
        BazarPageSubmitButton1.setFocusable(false);
        BazarPageSubmitButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BazarPageSubmitButton1.setIconTextGap(0);
        BazarPageSubmitButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BazarPageSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageSubmitButton1ActionPerformed(evt);
            }
        });
        BazarPanelUpPanel1.add(BazarPageSubmitButton1);
        BazarPageSubmitButton1.setBounds(170, 130, 100, 30);

        BazarPageAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageAmount.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageAmount.setText("Amount");
        BazarPanelUpPanel1.add(BazarPageAmount);
        BazarPageAmount.setBounds(350, 90, 60, 20);

        BazarPageAmountField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageAmountFieldActionPerformed(evt);
            }
        });
        BazarPanelUpPanel1.add(BazarPageAmountField);
        BazarPageAmountField.setBounds(420, 80, 130, 30);

        BazarPageItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageItem.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageItem.setText("Item");
        BazarPanelUpPanel1.add(BazarPageItem);
        BazarPageItem.setBounds(60, 90, 60, 20);

        BazarPageItemField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageItemField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageItemFieldActionPerformed(evt);
            }
        });
        BazarPanelUpPanel1.add(BazarPageItemField);
        BazarPageItemField.setBounds(120, 80, 190, 30);

        BazarPage.add(BazarPanelUpPanel1);
        BazarPanelUpPanel1.setBounds(200, 60, 600, 170);

        BazarDownPanel1.setBackground(new java.awt.Color(204, 204, 204));
        BazarDownPanel1.setLayout(null);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable2.setModel(modelforBazar);
        jTable2.setFocusable(false);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setOpaque(false);
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowGrid(false);
        jScrollPane2.setViewportView(jTable2);

        BazarDownPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 550, 160);

        BazarPage.add(BazarDownPanel1);
        BazarDownPanel1.setBounds(200, 210, 600, 290);

        getContentPane().add(BazarPage);
        BazarPage.setBounds(0, 0, 800, 500);

        BillPage.setBackground(new java.awt.Color(204, 204, 204));
        BillPage.setEnabled(false);
        BillPage.setLayout(null);

        BillPanelUpPanel2.setBackground(new java.awt.Color(25, 63, 97));
        BillPanelUpPanel2.setEnabled(false);
        BillPanelUpPanel2.setLayout(null);

        BazarPageName2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageName2.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageName2.setText("Name");
        BillPanelUpPanel2.add(BazarPageName2);
        BazarPageName2.setBounds(60, 30, 50, 20);

        BazarPageDate2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageDate2.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageDate2.setText("Date");
        BillPanelUpPanel2.add(BazarPageDate2);
        BazarPageDate2.setBounds(370, 30, 50, 20);

        BazarPageDateField2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BillPanelUpPanel2.add(BazarPageDateField2);
        BazarPageDateField2.setBounds(420, 26, 130, 30);

        BazarPageNameComboBox2.setEditable(true);
        BazarPageNameComboBox2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BazarPageNameComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(name));
        BazarPageNameComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BazarPageNameComboBox2.setFocusable(false);
        BazarPageNameComboBox2.setKeySelectionManager(null);
        BazarPageNameComboBox2.setLightWeightPopupEnabled(false);
        BazarPageNameComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageNameComboBox2ActionPerformed(evt);
            }
        });
        BillPanelUpPanel2.add(BazarPageNameComboBox2);
        BazarPageNameComboBox2.setBounds(120, 26, 190, 30);

        BazarPageEditButton2.setBackground(new java.awt.Color(25, 63, 97));
        BazarPageEditButton2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageEditButton2.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageEditButton2.setText("Delet");
        BazarPageEditButton2.setActionCommand("");
        BazarPageEditButton2.setBorder(null);
        BazarPageEditButton2.setBorderPainted(false);
        BazarPageEditButton2.setFocusPainted(false);
        BazarPageEditButton2.setFocusTraversalPolicyProvider(true);
        BazarPageEditButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BazarPageEditButton2.setIconTextGap(0);
        BazarPageEditButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BazarPageEditButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageEditButton2ActionPerformed(evt);
            }
        });
        BillPanelUpPanel2.add(BazarPageEditButton2);
        BazarPageEditButton2.setBounds(320, 130, 100, 30);

        BazarPageSubmitButton2.setBackground(new java.awt.Color(25, 63, 97));
        BazarPageSubmitButton2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageSubmitButton2.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageSubmitButton2.setText("Sumit");
        BazarPageSubmitButton2.setActionCommand("");
        BazarPageSubmitButton2.setBorder(null);
        BazarPageSubmitButton2.setBorderPainted(false);
        BazarPageSubmitButton2.setFocusPainted(false);
        BazarPageSubmitButton2.setFocusable(false);
        BazarPageSubmitButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BazarPageSubmitButton2.setIconTextGap(0);
        BazarPageSubmitButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BazarPageSubmitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageSubmitButton2ActionPerformed(evt);
            }
        });
        BillPanelUpPanel2.add(BazarPageSubmitButton2);
        BazarPageSubmitButton2.setBounds(170, 130, 100, 30);

        BazarPageAmount1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageAmount1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageAmount1.setText("Amount");
        BillPanelUpPanel2.add(BazarPageAmount1);
        BazarPageAmount1.setBounds(350, 90, 60, 20);

        BazarPageAmountField1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageAmountField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageAmountField1ActionPerformed(evt);
            }
        });
        BillPanelUpPanel2.add(BazarPageAmountField1);
        BazarPageAmountField1.setBounds(420, 80, 130, 30);

        BazarPageItem1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BazarPageItem1.setForeground(new java.awt.Color(255, 255, 255));
        BazarPageItem1.setText("Bill");
        BillPanelUpPanel2.add(BazarPageItem1);
        BazarPageItem1.setBounds(60, 90, 60, 20);

        BazarPageItemField1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        BazarPageItemField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BazarPageItemField1ActionPerformed(evt);
            }
        });
        BillPanelUpPanel2.add(BazarPageItemField1);
        BazarPageItemField1.setBounds(120, 80, 190, 30);

        BillPage.add(BillPanelUpPanel2);
        BillPanelUpPanel2.setBounds(200, 60, 600, 170);

        BillDownPanel2.setBackground(new java.awt.Color(204, 204, 204));
        BillDownPanel2.setLayout(null);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable3.setModel(modelforBill);
        jTable3.setFocusable(false);
        jTable3.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable3.setOpaque(false);
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.setShowGrid(false);
        jScrollPane3.setViewportView(jTable3);

        BillDownPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 60, 550, 160);

        BillPage.add(BillDownPanel2);
        BillDownPanel2.setBounds(200, 210, 600, 290);

        getContentPane().add(BillPage);
        BillPage.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainLeftPanelOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelOptionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainLeftPanelOptionButtonActionPerformed

    private void MainLeftPanelMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelMealButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(true);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelMealButtonActionPerformed

    private void MainLeftPanelBazarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelBazarButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(true);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelBazarButtonActionPerformed

    private void MainLeftPanelBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelBillButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(true);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelBillButtonActionPerformed

    private void MainLeftPanelAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelAmountButtonActionPerformed
        UserPage.setVisible(false);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(true);
    }//GEN-LAST:event_MainLeftPanelAmountButtonActionPerformed

    private void MainLeftPanelUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainLeftPanelUserButtonActionPerformed
        UserPage.setVisible(true);
        MealPage.setVisible(false);
        BazarPage.setVisible(false);
        BillPage.setVisible(false);
        AmountPage.setVisible(false);
    }//GEN-LAST:event_MainLeftPanelUserButtonActionPerformed

    private void TaslufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaslufActionPerformed
        UserPageRhymePanel.setVisible(true);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(false);
    }//GEN-LAST:event_TaslufActionPerformed

    private void TilokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TilokActionPerformed
        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(true);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(false);
    }//GEN-LAST:event_TilokActionPerformed

    private void MosarofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosarofActionPerformed
        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(false);
        UserPageMosarofPanel.setVisible(true);
    }//GEN-LAST:event_MosarofActionPerformed

    private void IshtiaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IshtiaqActionPerformed

        UserPageRhymePanel.setVisible(false);
        UserPageTilokPanel.setVisible(false);
        UserPageIshtiaqPanel.setVisible(true);
        UserPageMosarofPanel.setVisible(false);

    }//GEN-LAST:event_IshtiaqActionPerformed

    private void MealPageNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageNameComboBoxActionPerformed
           
    }//GEN-LAST:event_MealPageNameComboBoxActionPerformed

    private void MealPageBreakFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageBreakFastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageBreakFastActionPerformed

    private void MealPageLunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageLunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealPageLunchActionPerformed

    private void MealPageSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageSubmitButtonActionPerformed
        if(evt.getSource() == MealPageSubmitButton)
        {
            int bf = 0;
            int l = 0;
            int d = 0;
            row[0] = this.MealPageNameComboBox.getSelectedItem().toString();
            if(this.MealPageBreakFast.isSelected())
            {
                bf = 1;
            }
            row[1] = Integer.toString(bf);
            if(this.MealPageLunch.isSelected())
            {
                l = 1;
            }
            row[2] = Integer.toString(l);
            if(this.MealPageDinner.isSelected())
            {
                d = 1;
            }
            row[3] = Integer.toString(d);
            row[4] = Integer.toString(bf+l+d);
            row[5] = this.MealPageDateField.getText();
            model.addRow(row);
        }
        
    }//GEN-LAST:event_MealPageSubmitButtonActionPerformed

    private void MealPageEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPageEditButtonActionPerformed
        int numerOfRow = this.jTable1.getSelectedRow();
        if(numerOfRow >= 0)
        {
            model.removeRow(numerOfRow);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row has been selected or no row exists");
        }
    }//GEN-LAST:event_MealPageEditButtonActionPerformed

    private void BazarPageNameComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageNameComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageNameComboBox1ActionPerformed

    private void BazarPageEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageEditButton1ActionPerformed
        int numerOfRow = this.jTable2.getSelectedRow();
        if(numerOfRow >= 0)
        {
            modelforBazar.removeRow(numerOfRow);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row has been selected or no row exists");
        }
    }//GEN-LAST:event_BazarPageEditButton1ActionPerformed

    private void BazarPageSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageSubmitButton1ActionPerformed
        rowForBazar[0] = this.BazarPageNameComboBox1.getSelectedItem().toString();
        rowForBazar[1] = this.BazarPageItemField.getText();
        rowForBazar[2] = this.BazarPageAmountField.getText();
        rowForBazar[3] = this.BazarPageDateField1.getText();
        modelforBazar.addRow(rowForBazar);
    }//GEN-LAST:event_BazarPageSubmitButton1ActionPerformed

    private void BazarPageAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageAmountFieldActionPerformed

    private void BazarPageItemFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageItemFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageItemFieldActionPerformed

    private void BazarPageNameComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageNameComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageNameComboBox2ActionPerformed

    private void BazarPageEditButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageEditButton2ActionPerformed
        int numerOfRow = this.jTable3.getSelectedRow();
        if(numerOfRow >= 0)
        {
            modelforBill.removeRow(numerOfRow);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row has been selected or no row exists");
        }
    }//GEN-LAST:event_BazarPageEditButton2ActionPerformed

    private void BazarPageSubmitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageSubmitButton2ActionPerformed
        rowForBill[0] = this.BazarPageNameComboBox2.getSelectedItem().toString();
        rowForBill[1] = this.BazarPageItemField1.getText();
        rowForBill[2] = this.BazarPageAmountField1.getText();
        rowForBill[3] = this.BazarPageDateField2.getText();
        modelforBill.addRow(rowForBill);
    }//GEN-LAST:event_BazarPageSubmitButton2ActionPerformed

    private void BazarPageAmountField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageAmountField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageAmountField1ActionPerformed

    private void BazarPageItemField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BazarPageItemField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BazarPageItemField1ActionPerformed

    private void Ishtiaq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ishtiaq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ishtiaq1ActionPerformed

    private void Tasluf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tasluf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tasluf1ActionPerformed

    private void Tilok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tilok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tilok1ActionPerformed

    private void Mosarof1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mosarof1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mosarof1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Address3;
    private javax.swing.JPanel AmountPage;
    private javax.swing.JPanel AmountPageDownPanel;
    private javax.swing.JPanel AmountPageUpPanel1;
    private javax.swing.JPanel BazarDownPanel1;
    private javax.swing.JPanel BazarPage;
    private javax.swing.JLabel BazarPageAmount;
    private javax.swing.JLabel BazarPageAmount1;
    private javax.swing.JTextField BazarPageAmountField;
    private javax.swing.JTextField BazarPageAmountField1;
    private javax.swing.JLabel BazarPageDate1;
    private javax.swing.JLabel BazarPageDate2;
    private javax.swing.JTextField BazarPageDateField1;
    private javax.swing.JTextField BazarPageDateField2;
    private javax.swing.JButton BazarPageEditButton1;
    private javax.swing.JButton BazarPageEditButton2;
    private javax.swing.JLabel BazarPageItem;
    private javax.swing.JLabel BazarPageItem1;
    private javax.swing.JTextField BazarPageItemField;
    private javax.swing.JTextField BazarPageItemField1;
    private javax.swing.JLabel BazarPageName1;
    private javax.swing.JLabel BazarPageName2;
    private javax.swing.JComboBox<String> BazarPageNameComboBox1;
    private javax.swing.JComboBox<String> BazarPageNameComboBox2;
    private javax.swing.JButton BazarPageSubmitButton1;
    private javax.swing.JButton BazarPageSubmitButton2;
    private javax.swing.JPanel BazarPanelUpPanel1;
    private javax.swing.JPanel BillDownPanel2;
    private javax.swing.JPanel BillPage;
    private javax.swing.JPanel BillPanelUpPanel2;
    private javax.swing.JLabel Blood;
    private javax.swing.JLabel Blood1;
    private javax.swing.JLabel Blood2;
    private javax.swing.JLabel Blood3;
    private javax.swing.JButton Ishtiaq;
    private javax.swing.JButton Ishtiaq1;
    private javax.swing.JPanel MainLeftPanel;
    private javax.swing.JButton MainLeftPanelAmountButton;
    private javax.swing.JLabel MainLeftPanelAmountIcon;
    private javax.swing.JButton MainLeftPanelBazarButton;
    private javax.swing.JLabel MainLeftPanelBazarIcon;
    private javax.swing.JButton MainLeftPanelBillButton;
    private javax.swing.JLabel MainLeftPanelBillIcon;
    private javax.swing.JButton MainLeftPanelMealButton;
    private javax.swing.JLabel MainLeftPanelMealIcon;
    private javax.swing.JButton MainLeftPanelOptionButton;
    private javax.swing.JLabel MainLeftPanelOptionIcon;
    private javax.swing.JButton MainLeftPanelUserButton;
    private javax.swing.JLabel MainLeftPanelUserIcon;
    private javax.swing.JPanel MealPage;
    private javax.swing.JCheckBox MealPageBreakFast;
    private javax.swing.JLabel MealPageDate;
    private javax.swing.JTextField MealPageDateField;
    private javax.swing.JCheckBox MealPageDinner;
    private javax.swing.JButton MealPageEditButton;
    private javax.swing.JCheckBox MealPageLunch;
    private javax.swing.JLabel MealPageName;
    private javax.swing.JComboBox<String> MealPageNameComboBox;
    private javax.swing.JButton MealPageSubmitButton;
    private javax.swing.JPanel MealPanelDownPanel;
    private javax.swing.JPanel MealPanelUpPanel;
    private javax.swing.JLabel Mobile;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JLabel Mobile2;
    private javax.swing.JLabel Mobile3;
    private javax.swing.JButton Mosarof;
    private javax.swing.JButton Mosarof1;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JButton Tasluf;
    private javax.swing.JButton Tasluf1;
    private javax.swing.JButton Tilok;
    private javax.swing.JButton Tilok1;
    private javax.swing.JLabel User;
    private javax.swing.JLabel User1;
    private javax.swing.JLabel User2;
    private javax.swing.JLabel User3;
    private javax.swing.JLabel User4;
    private javax.swing.JLabel User5;
    private javax.swing.JLabel User6;
    private javax.swing.JLabel User7;
    private javax.swing.JPanel UserPage;
    private javax.swing.JPanel UserPageIshtiaqPanel;
    private javax.swing.JPanel UserPageMosarofPanel;
    private javax.swing.JPanel UserPageRhymePanel;
    private javax.swing.JPanel UserPageTilokPanel;
    private javax.swing.JPanel UserPageUpPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
